#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_SPI_HOST VSPI_HOST 
#define CONFIG_SPI_SCLK 18 
#define CONFIG_SPI_MISO 19 
#define CONFIG_SPI_MOSI 23

#define CONFIG_LCD_DC 32
#define CONFIG_LCD_CS 14
#define CONFIG_LCD_RST 33

#define CONFIG_TOUCH_CS 0

#define CONFIG_MOTOR_DIR 0
#define CONFIG_MOTOR_STEP 15
#define CONFIG_MOTOR_SW 13

#define CONFIG_D0 4
#define CONFIG_D1 5
#define CONFIG_D2 16
#define CONFIG_D3 17
#define CONFIG_D4 36
#define CONFIG_D5 39
#define CONFIG_D6 34
#define CONFIG_D7 35
#define CONFIG_XCLK 21
#define CONFIG_PCLK 22
#define CONFIG_VSYNC 25
#define CONFIG_HREF 3
#define CONFIG_SDA 26
#define CONFIG_SCL 27
#define CONFIG_RESET 2
#define CONFIG_XCLK_FREQ 8000000

#endif
